[package]
name = "chladni-plates"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = {version="0.4.4", default-features = false}

[features]

default = ["oscillations"]

oscillations = []

plate = []
